# Generated by Django 5.1.7 on 2025-03-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("dispatcher", "dispatcher"),
                    ("driver", "driver"),
                    ("technician", "technician"),
                    ("admin", "admin"),
                    ("carrier manager", "carrier manager"),
                ],
                default="driver",
                max_length=50,
            ),
        ),
    ]
