# Generated by Django 5.1.7 on 2025-03-21 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fleet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdverseDrivingCondition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_at", models.DateTimeField(auto_now_add=True)),
                ("end_at", models.DateTimeField()),
                ("description", models.TextField()),
                ("extended_driving_time", models.FloatField()),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adverse_driving_conditions",
                        to="fleet.driver",
                    ),
                ),
            ],
            options={
                "db_table": "adverse_driving_conditions",
            },
        ),
        migrations.CreateModel(
            name="DutyStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_at", models.DateTimeField(auto_now_add=True)),
                ("end_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OFF_DUTY", "Off Duty"),
                            ("ON_DUTY", "On Duty"),
                            ("DRIVING", "Driving"),
                            ("SLEEPER_BERTH", "Sleeper Berth"),
                        ],
                        db_index=True,
                        max_length=15,
                    ),
                ),
                ("location", models.CharField(max_length=95)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_statuses",
                        to="fleet.driver",
                    ),
                ),
            ],
            options={
                "db_table": "duty_statuses",
            },
        ),
        migrations.CreateModel(
            name="DutyRemark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "duty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_remarks",
                        to="compliance.dutystatus",
                    ),
                ),
            ],
            options={
                "db_table": "duty_remarks",
            },
        ),
        migrations.CreateModel(
            name="OnDutyLimit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField()),
                ("is_7_day", models.BooleanField(default=True)),
                ("total_hours", models.FloatField()),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_limits",
                        to="fleet.driver",
                    ),
                ),
            ],
            options={
                "db_table": "duty_limits",
            },
        ),
        migrations.CreateModel(
            name="OtherDuty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_at", models.DateTimeField(auto_now_add=True)),
                ("end_at", models.DateTimeField()),
                ("location", models.CharField(max_length=95)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PERSONAL_CONVEYANCE", "Personal Conveyance"),
                            ("YARD_MOVE", "Yard Move"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_duties",
                        to="fleet.driver",
                    ),
                ),
            ],
            options={
                "db_table": "other_duties",
            },
        ),
        migrations.CreateModel(
            name="Restart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_at", models.DateTimeField(auto_now_add=True)),
                ("end_at", models.DateTimeField()),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restarts",
                        to="fleet.driver",
                    ),
                ),
            ],
            options={
                "db_table": "restarts",
            },
        ),
        migrations.CreateModel(
            name="RestBreak",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_at", models.DateTimeField(auto_now_add=True)),
                ("end_at", models.DateTimeField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("OFF_DUTY", "Off Duty"),
                            ("ON_DUTY", "On Duty Not Driving"),
                            ("SLEEPER_BERTH", "Sleeper Berth"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rest_breaks",
                        to="fleet.driver",
                    ),
                ),
            ],
            options={
                "db_table": "rest_breaks",
            },
        ),
        migrations.CreateModel(
            name="ShortHaul",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateTimeField()),
                ("is_cdl", models.BooleanField(default=False)),
                ("radius_miles", models.FloatField()),
                ("return_time", models.DateTimeField()),
                ("description", models.TextField()),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="short_haul_exceptions",
                        to="fleet.driver",
                    ),
                ),
            ],
            options={
                "db_table": "short_haul_exceptions",
            },
        ),
        migrations.CreateModel(
            name="ShortHaulRemark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "short_haul",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="short_haul_remarks",
                        to="compliance.shorthaul",
                    ),
                ),
            ],
            options={
                "db_table": "short_haul_remarks",
            },
        ),
        migrations.CreateModel(
            name="SleeperBerth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_at", models.DateTimeField(auto_now_add=True)),
                ("end_at", models.DateTimeField()),
                ("is_qualified", models.BooleanField(default=False)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sleeper_berths",
                        to="fleet.driver",
                    ),
                ),
            ],
            options={
                "db_table": "sleeper_berths",
            },
        ),
    ]
