# Generated by Django 5.1.7 on 2025-03-18 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compliance", "0001_initial"),
        ("fleet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adversedrivingcondition",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adverse_driving_conditions",
                to="fleet.driver",
            ),
        ),
        migrations.AddField(
            model_name="dutystatus",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="duty_statuses",
                to="fleet.driver",
            ),
        ),
        migrations.AddField(
            model_name="dutyremark",
            name="duty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="duty_remarks",
                to="compliance.dutystatus",
            ),
        ),
        migrations.AddField(
            model_name="ondutylimit",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="duty_limits",
                to="fleet.driver",
            ),
        ),
        migrations.AddField(
            model_name="otherduty",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="other_duties",
                to="fleet.driver",
            ),
        ),
        migrations.AddField(
            model_name="restart",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restarts",
                to="fleet.driver",
            ),
        ),
        migrations.AddField(
            model_name="restbreak",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rest_breaks",
                to="fleet.driver",
            ),
        ),
        migrations.AddField(
            model_name="shorthaul",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="short_haul_exceptions",
                to="fleet.driver",
            ),
        ),
        migrations.AddField(
            model_name="shorthaulremark",
            name="short_haul",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="short_haul_remarks",
                to="compliance.shorthaul",
            ),
        ),
        migrations.AddField(
            model_name="sleeperberth",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sleeper_berths",
                to="fleet.driver",
            ),
        ),
    ]
