# Generated by Django 5.1.7 on 2025-03-28 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
        ("fleet", "0002_alter_carrier_options_alter_driver_license_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adversedrivingcondition",
            name="end_at",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="dutystatus",
            name="end_at",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="dutystatus",
            name="location",
            field=models.CharField(
                max_length=95, validators=[django.core.validators.MinLengthValidator(3)]
            ),
        ),
        migrations.AlterField(
            model_name="dutystatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("OFF_DUTY", "OFF DUTY"),
                    ("ON_DUTY", "ON DUTY"),
                    ("DRIVING", "DRIVING"),
                    ("SLEEPER_BERTH", "SLEEPER BERTH"),
                ],
                db_index=True,
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="otherduty",
            name="end_at",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="restart",
            name="end_at",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="restbreak",
            name="end_at",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="sleeperberth",
            name="end_at",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AddConstraint(
            model_name="dutystatus",
            constraint=models.UniqueConstraint(
                condition=models.Q(("end_at__isnull", True)),
                fields=("driver", "end_at"),
                name="unique_active_status_per_driver",
            ),
        ),
    ]
