# Generated by Django 5.1.7 on 2025-04-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0002_alter_adversedrivingcondition_end_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restart",
            old_name="is_complete",
            new_name="is_completed",
        ),
    ]
