# Generated by Django 5.1.7 on 2025-03-31 10:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0002_alter_carrier_options_alter_driver_license_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="mileage_week",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="total_mileage_driven",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
