# Generated by Django 5.1.7 on 2025-03-18 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fleet", "0001_initial"),
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "total_miles_driven",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to="fleet.driver",
                    ),
                ),
                (
                    "shipping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to="shipping.shipping",
                    ),
                ),
                (
                    "trailers",
                    models.ManyToManyField(
                        blank=True, related_name="daily_logs", to="fleet.trailer"
                    ),
                ),
                (
                    "truck",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to="fleet.truck",
                    ),
                ),
            ],
            options={
                "db_table": "daily_logs",
            },
        ),
    ]
