name: Deploy SpotterRDS Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      BACKEND_PATH: ./backend/spotterrods

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${DOCKERHUB_USERNAME}
          password: ${DOCKERHUB_TOKEN}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ${BACKEND_PATH}
          push: true
          tags: "${DOCKERHUB_USERNAME}/spotterrods-api:latest"